[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "cephfs_srr"
version = "1.1.0"
dependencies = []

[project.scripts]
storage_summary = "cephfs_srr.storage_summary:main"
